#spring:
#  ai:
#    openai:
#      api-key:
#      base-url: https://api.deepseek.com
#      chat:
#        options:
#          model: deepseek-reasoner
#          temperature: 0.7
#      embedding:
#        enabled: false


spring:
  ai:
    openai:
      base-url: https://api.openai.com
      api-key:
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
      embedding:
        enabled: false


    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:7b

